modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="tims_essential_commands"
version="1.0.0"
displayName="Tims Essential Commands"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="timpi_t1u1mz0, MCreator"

[[dependencies.tims_essential_commands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




